### ISSUE TITLE
Ransomware S3 Bucket Encryption Rule

### ISSUE THREAD

**Issue by kickroot** [openraven/magpie#210]
https://docs.aws.amazon.com/AmazonS3/latest/userguide/default-bucket-encryption.html

**Comment by kickroot** [comment]
We want to check for buckets set to encrypt with a KMS key that belongs to a different account.

**Comment by curphey** [comment]
To be clear this rule is to detect this scenario https://rhinosecuritylabs.com/aws/s3-ransomware-part-1-attack-vector/

**Comment by belosh59** [comment]
@curphey @kickroot 
Added another rule for checking the KMS Keys belong to the same S3 Bucket owner account_id.

Reproducing rule violation steps:
1. Chose bucket with Server side enabled security with KMS (or enable it by yourself) 
2. Update the S3 bucket account_id to some another one which doesnt match the assigned KMS Key
```
update assets
set account_id = '1234'
where asset_id = 'arn:aws:s3:::surprise-bucket';
```
3.  Rule statement retuns:
```
select s3bucket.asset_id, s3bucket.account_id, arr.ssec -> 'applyServerSideEncryptionByDefault' ->> 'kmsMasterKeyID'
  from assets s3bucket, 
  LATERAL (
      SELECT value AS ssec
      FROM jsonb_array_elements(s3bucket.supplementary_configuration -> 'serverSideEncryptionConfiguration' -> 'rules')
  ) arr
  where s3bucket.resource_type = 'AWS::S3::Bucket'
    and arr.ssec ->> 'bucketKeyEnabled' = 'true'
    and arr.ssec -> 'applyServerSideEncryptionByDefault' ->> 'sseAlgorithm' = 'aws:kms';
--    and arr.ssec -> 'applyServerSideEncryptionByDefault' ->> 'kmsMasterKeyID' not like '%:'||s3bucket.account_id||':%';
```
<img width="1089" alt="Screenshot 2021-08-18 at 19 53 32" src="https://user-images.githubusercontent.com/26186899/129939894-b5d0eefa-6e34-4e93-8d14-aebef7c9aa84.png">
If you will uncomment the last SQL line the result will be `surprise-bucket`

**Comment by belosh59** [comment]
**Proposal for initial rule improvement**: aws_s3_bucket_encryption_enabled
Enabling the Default `Server Side Encryption` with specified `KMS Key` could save contents preview if attackers doesn't have grant for used KMS key to encrypt the file. See the following:
https://rhinosecuritylabs.com/aws/s3-ransomware-part-1-attack-vector/#:~:text=AWS%20KMS%20integrates,your%20own%20files.

But if attackers escalates and gain 's3:PutObject' permission, they still will be able to override the default KMS encryption with their own provided cross-account KMS Key:
<img width="889" alt="Screenshot 2021-08-18 at 20 25 03" src="https://user-images.githubusercontent.com/26186899/129944233-e32b6316-ead1-4e5c-bf2c-adb19e7e024e.png">

So in order to prevent attackers to Override the `Default KMS Key` Rhino Labs suggest to define policy allowing object updates in the current S3 Bucket only with the specified KMS Key and reject updates with other KMS Keys

**Comment by belosh59** [comment]
Issue has been closed
