### ISSUE TITLE
[Bug] Assets of different types being replaced one over another

### ISSUE THREAD

**Issue by belosh59** [openraven/magpie#272]
Bug was found and reproduced in AWS and GCP discovery scenario.

Description:
- magpie-discovery being executed for AWS IAM services
- Several assets with different resource_types were generated:

1. `arn:aws:iam::723176279592:user/janea` of type `AWS::IAM::User`
2. `arn:aws:iam::723176279592:user/janea` of type `AWS::IAM::CredentialsReport`

**Expected result:**
- Both assets being saved successfully 

**Actual result**
- Only one asset with type `AWS::IAM::User` appear in DB since this type is grabbed last and it was able to override the one with `AWS::IAM::CredentialsReport` coz they share the same `asset_id`

**Comment by mike-m-andrews** [comment]
This is because in Magpie each resource is written to the same table. In aws-discovery, as they are independent tables per resource-type there isn’t that problem.

I’m doing some work now in aws-discovery that’s addresses a somewhat different problem, but same solution - I’ll point you to it, but there’s two things playing together here…

1. That ARN on its own isn’t unique. This is against user credential reports, but you’ll see the same behavior with SSMInstsnce overwriting EC2 - they both use ARNs of the resource they are augmenting. So, quick fix maybe to have ARN+ResourceType be the primary key/lookup.
2. These aren’t really assets/resources - they are extended properties of other. (Real) resources - IAMUser (or EC2Instances). It’s better to either appended them as configuration to these resources, or (as I am going to do) save to a separate table and join them to their real resources when needed.
